// Generated by scripts/extract-svg-text.mjs from public/boardbook/waterkringloop.svg. Do not edit.
import type { TextLine } from './TextLayer'

export const WATERKRINGLOOP_TEXT: TextLine[] = [
  {
    "text": "3.2  De waterkringloop",
    "x": 5,
    "y": 2.739,
    "width": 27.204,
    "height": 4.594,
    "fontSize": 2.75
  },
  {
    "text": "Aardrijkskunde · groep 7",
    "x": 86.25,
    "y": 4.682,
    "width": 14.346,
    "height": 2.297,
    "fontSize": 1.375
  },
  {
    "text": "Water is altijd in beweging. Het verdampt uit de zee, stijgt op als waterdamp,",
    "x": 5,
    "y": 14.134,
    "width": 43.151,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "vormt wolken en valt als regen of sneeuw weer naar beneden. Daarna stroomt het",
    "x": 5,
    "y": 16.961,
    "width": 46.21,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "via rivieren terug naar de zee. Die rondgang noemen we de waterkringloop.",
    "x": 5,
    "y": 19.788,
    "width": 42.415,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "Hij houdt nooit op — het water dat jij vandaag drinkt, was ooit onderdeel van",
    "x": 5,
    "y": 22.615,
    "width": 42.95,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "een wolk boven de oceaan.",
    "x": 5,
    "y": 25.442,
    "width": 15.41,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "Verdamping",
    "x": 5,
    "y": 32.774,
    "width": 10.303,
    "height": 3.092,
    "fontSize": 1.875
  },
  {
    "text": "De zon verwarmt het water in zeeën, meren en rivieren. Een deel van dat water",
    "x": 5,
    "y": 37.102,
    "width": 44.262,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "verandert in waterdamp: een gas dat je niet kunt zien. Hoe warmer het is, hoe",
    "x": 5,
    "y": 39.929,
    "width": 43.691,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "sneller water verdampt. Ook planten geven waterdamp af via hun bladeren.",
    "x": 5,
    "y": 42.756,
    "width": 42.441,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "Neerslag",
    "x": 5,
    "y": 49.558,
    "width": 7.648,
    "height": 3.092,
    "fontSize": 1.875
  },
  {
    "text": "Hoog in de lucht is het koud. De waterdamp condenseert tot piepkleine",
    "x": 5,
    "y": 53.887,
    "width": 40.274,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "druppeltjes en vormt wolken. Worden de druppels te zwaar, dan vallen ze als",
    "x": 5,
    "y": 56.714,
    "width": 43.19,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "regen, hagel of sneeuw naar beneden. Dat heet neerslag.",
    "x": 5,
    "y": 59.541,
    "width": 32.358,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "verdamping",
    "x": 51.25,
    "y": 42.314,
    "width": 7.441,
    "height": 2.297,
    "fontSize": 1.375
  },
  {
    "text": "condensatie",
    "x": 62.5,
    "y": 13.163,
    "width": 7.709,
    "height": 2.297,
    "fontSize": 1.375
  },
  {
    "text": "neerslag",
    "x": 78.125,
    "y": 27.297,
    "width": 5.401,
    "height": 2.297,
    "fontSize": 1.375
  },
  {
    "text": "afstroming",
    "x": 67.5,
    "y": 65.283,
    "width": 6.789,
    "height": 2.297,
    "fontSize": 1.375
  },
  {
    "text": "Opdracht 3",
    "x": 6.5,
    "y": 78.71,
    "width": 8.38,
    "height": 2.65,
    "fontSize": 1.625
  },
  {
    "text": "1.  Waardoor verdampt water uit de zee? Schrijf twee oorzaken op.",
    "x": 6.5,
    "y": 84.364,
    "width": 37.06,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "2.  Leg in je eigen woorden uit wat condensatie is.",
    "x": 6.5,
    "y": 87.898,
    "width": 27.742,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "3.  Teken de pijl van de kringloop die ontbreekt in de afbeelding.",
    "x": 6.5,
    "y": 91.431,
    "width": 35.726,
    "height": 2.12,
    "fontSize": 1.313
  },
  {
    "text": "blz. 42",
    "x": 88.75,
    "y": 96.908,
    "width": 3.095,
    "height": 1.59,
    "fontSize": 1
  }
]
